package net.cn.mgw.api.user.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.truename
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_card
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.portrait
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_lock
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.add_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_delete
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.delete_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_update_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.truename
     *
     * @return the value of user.truename
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.truename
     *
     * @param truename the value for user.truename
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setTruename(Integer truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_card
     *
     * @return the value of user.id_card
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_card
     *
     * @param idCard the value for user.id_card
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setIdCard(Integer idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.portrait
     *
     * @return the value of user.portrait
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.portrait
     *
     * @param portrait the value for user.portrait
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_lock
     *
     * @return the value of user.is_lock
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_lock
     *
     * @param isLock the value for user.is_lock
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.add_time
     *
     * @return the value of user.add_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.add_time
     *
     * @param addTime the value for user.add_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_delete
     *
     * @return the value of user.is_delete
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_delete
     *
     * @param isDelete the value for user.is_delete
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.delete_time
     *
     * @return the value of user.delete_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.delete_time
     *
     * @param deleteTime the value for user.delete_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_update_time
     *
     * @return the value of user.last_update_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_update_time
     *
     * @param lastUpdateTime the value for user.last_update_time
     *
     * @mbggenerated Sun Nov 19 13:06:37 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}